project:
  type: website

website:
  title: "Yiqian Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: notes.qmd
        text: Mathematical Notes
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-copy: true
    include-in-header:
      text: |
        <meta name="robots" content="noindex, nofollow">